name: 🐛 Bug Report
description: Report a bug or issue with the PRD Workflow Manager plugin
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component is affected?
      description: Select the component where you encountered the bug
      options:
        - Command (/review-prd)
        - Command (/code-prd)
        - Command (/work-prd)
        - Command (/list-prds)
        - Command (/create-prd)
        - Command (/archive-prd)
        - Command (/security-audit)
        - Command (/quality-check)
        - Command (/orchestrate)
        - Agent (prd-reviewer)
        - Agent (prd-implementer)
        - Agent (orchestrator)
        - Agent (security-expert)
        - Agent (quality-assurance)
        - Agent (devops-engineer)
        - Skill (git-workflow)
        - Skill (testing)
        - Skill (security-analysis)
        - Skill (code-quality)
        - Skill (documentation)
        - Skill (estimation)
        - Skill (dependency-management)
        - Skill (performance-analysis)
        - Configuration
        - Template
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Messages / Logs
      description: If applicable, paste any error messages or relevant logs
      placeholder: |
        Paste error messages here
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (blocks all usage)
        - High (blocks major functionality)
        - Medium (affects some functionality)
        - Low (minor inconvenience)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: What version of PRD Workflow Manager are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Claude Code Version
      description: What version of Claude Code are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Paste your plugin configuration (remove any sensitive information)
      placeholder: |
        {
          "prd_workflow": {
            "enabled": true,
            ...
          }
        }
      render: json

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, project structure, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I am using the latest version of the plugin
          required: false
