name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'  # Déclenché sur les tags v1.0.0, v1.1.0, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"

          # Extract section from CHANGELOG.md between [VERSION] and next version
          CHANGELOG=$(sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d' | tail -n +2)

          # If empty, use a default message
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="See [CHANGELOG.md](https://github.com/Yassinello/claude-prd-workflow/blob/main/CHANGELOG.md) for details."
          fi

          # Save to file for multiline support
          echo "$CHANGELOG" > /tmp/changelog.txt

          # Also save to output
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ steps.get_version.outputs.VERSION }}"
          body_path: /tmp/changelog.txt
          draft: false
          prerelease: false
          generate_release_notes: true  # Auto-generate from commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        run: |
          echo "## 🎉 GitHub Release Created" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release URL**: https://github.com/Yassinello/claude-prd-workflow/releases/tag/${{ steps.get_version.outputs.TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Changelog" >> $GITHUB_STEP_SUMMARY
          cat /tmp/changelog.txt >> $GITHUB_STEP_SUMMARY
